apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx   
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset1
  labels:
    app: my-nginx
spec:
  selector:
    matchLabels:
      app: nginx   
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset2
  labels:
    app: my-nginx
spec:
  selector:
    matchLabels:
      app: nginx   
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
    