apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app
  labels:
    app: ip-app
  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app   
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
        - name: ip-app
          image: dayashankarmm/my_image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-ip
spec:
  type: NodePort
  selector:
    app: ip-app
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     nodePort: 30028
