apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip_app
  labels:
    app: ip_app
  namespace: mypod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip_app   
  template:
    metadata:
      labels:
        app: ip_app
    spec:
      containers:
        - name: ip_app
          image: dayashankarmm/my_image:latest

          ports:
            - containerPort: 8080
